Repository duality-solutions/Dynamic, pull requests merged in 2018-09, with the labels that each got.

#202 Remove double forcecompactdb arg
  src/dbwrapper.cpp
Labels: review

#201 Remove duplicate mem pool check in available coins
  src/wallet/wallet.cpp
Labels: review

#169 [GPU] Mining with autotune
  .gitignore
  .travis.yml
  README.md
  build-aux/m4/ax_check_cuda.m4
  build-aux/m4/ax_normalize_path.m4
  configure.ac
  src/Makefile.am
  src/Makefile.gpu.include
  src/Makefile.qt.include
  src/Makefile.qttest.include
  src/Makefile.test.include
  src/bdap/domainentry.h
  src/crypto/argon2gpu/blake2b.cpp
  src/crypto/argon2gpu/blake2b.h
  src/crypto/argon2gpu/common.cpp
  src/crypto/argon2gpu/common.h
  src/crypto/argon2gpu/cuda/cuda-exception.h
  src/crypto/argon2gpu/cuda/device.cpp
  src/crypto/argon2gpu/cuda/device.h
  src/crypto/argon2gpu/cuda/global-context.cpp
  src/crypto/argon2gpu/cuda/global-context.h
  src/crypto/argon2gpu/cuda/kernels.cu
  src/crypto/argon2gpu/cuda/kernels.h
  src/crypto/argon2gpu/cuda/processing-unit.cpp
  src/crypto/argon2gpu/cuda/processing-unit.h
  src/crypto/argon2gpu/cuda/program-context.cpp
  src/crypto/argon2gpu/cuda/program-context.h
  src/crypto/argon2gpu/opencl/cl.hpp
  src/crypto/argon2gpu/opencl/device.cpp
  src/crypto/argon2gpu/opencl/device.h
  src/crypto/argon2gpu/opencl/global-context.cpp
  src/crypto/argon2gpu/opencl/global-context.h
  src/crypto/argon2gpu/opencl/kernel-loader.cpp
  src/crypto/argon2gpu/opencl/kernel-loader.h
  src/crypto/argon2gpu/opencl/kernel-runner.cpp
  src/crypto/argon2gpu/opencl/kernel-runner.h
  src/crypto/argon2gpu/opencl/kernel.cl
  src/crypto/argon2gpu/opencl/opencl.h
  src/crypto/argon2gpu/opencl/processing-unit.cpp
  src/crypto/argon2gpu/opencl/processing-unit.h
  src/crypto/argon2gpu/opencl/program-context.cpp
  src/crypto/argon2gpu/opencl/program-context.h
  src/init.cpp
  src/miner-gpu.h
  src/miner.cpp
  src/miner.h
  src/qt/forms/miningpage.ui
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/hashrategraphwidget.cpp
  src/qt/hashrategraphwidget.h
  src/qt/miningpage.cpp
  src/qt/miningpage.h
  src/rpcclient.cpp
  src/rpcmining.cpp
  src/test/miner_tests.cpp
Labels: in progress

#208 Fixes memory use (v2.3.5)
  CHANGELOG.md
  configure.ac
  doc/release-notes.md
  src/Makefile.am
  src/chain.cpp
  src/chain.h
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/dynode-payments.cpp
  src/dynode-payments.h
  src/dynode.cpp
  src/fluid/fluid.cpp
  src/fluid/fluid.h
  src/fluid/fluiddb.cpp
  src/fluid/fluiddb.h
  src/fluid/fluiddynode.cpp
  src/fluid/fluiddynode.h
  src/fluid/fluidmining.cpp
  src/fluid/fluidmining.h
  src/fluid/fluidmint.cpp
  src/fluid/fluidmint.h
  src/fluid/fluidsovereign.cpp
  src/fluid/fluidsovereign.h
  src/fluid/rpcfluid.cpp
  src/init.cpp
  src/miner.cpp
  src/qt/transactionrecord.cpp
  src/txdb.cpp
  src/validation.cpp
  src/version.h
  src/wallet/wallet.cpp
Labels: bug
